export const scheduleLinks = [
  { id: 1, time: "07-16" },
  { id: 2, time: "08-17" },
  { id: 3, time: "09-18" },
  { id: 4, time: "11-20" },
  { id: 5, time: "13-22" },
  { id: 6, time: "15-24" },
  { id: 7, time: "17-02" },
];

export const supervisors = [
  {
    id: 1,
    title: "Shahriyor",
    link: "supervisor-1",
  },
  {
    id: 2,
    title: "Turg'unov Abduqodir Jo'rayevich",
    link: "supervisor-2",
  },
  {
    id: 3,
    title: "Izzat",
    link: "supervisor-3",
  },
  {
    id: 4,
    title: "Yusupova Nargiza Abrorovna",
    link: "supervisor-4",
  },
];

export const checkboxGroupData = [
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: true,
    label: 2,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: true,
    isNight: false,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
  },
];
