import { ICheckbox } from "@shared/lib/types";

export const scheduleLinks = [
  { id: 1, time: "07-16", isSelected: true },
  { id: 2, time: "08-17", isSelected: false },
  { id: 3, time: "09-18", isSelected: false },
  { id: 4, time: "11-20", isSelected: false },
  { id: 5, time: "13-22", isSelected: false },
  { id: 6, time: "15-24", isSelected: false },
  { id: 7, time: "17-02", isSelected: false },
];

export const supervisors = [
  {
    id: 1,
    title: "Shahriyor",
    link: "supervisor-1",
  },
  {
    id: 2,
    title: "Turg'unov Abduqodir Jo'rayevich",
    link: "supervisor-2",
  },
  {
    id: 3,
    title: "Izzat",
    link: "supervisor-3",
  },
  {
    id: 4,
    title: "Yusupova Nargiza Abrorovna",
    link: "supervisor-4",
  },
];

export const checkboxGroupData: ICheckbox[] = [
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: true,
    label: 2,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: true,
    isNight: false,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
  {
    id: 1,
    isWorkDay: true,
    isOrder: false,
    isNight: true,
    isHoliday: false,
    isToday: false,
    isCheckable: false,
    label: 1,
    shouldBeOffday: false,
  },
];

export const currentScheduleData = [
  {
    id: 1,
    title: "Сегодня у вас:",
    value: "Рабочий день",
  },
  {
    id: 2,
    title: "Основные входные дни:",
    value: "Пн-Вт",
  },
  {
    id: 3,
    title: "Кол-во рабочих дней:",
    value: "22",
  },
  {
    id: 4,
    title: "Продуктивность:",
    value: "87%",
  },
];

export const layoutData = [
  {
    id: 1,
    title: "Календарные дни",
    value: "31",
  },
  {
    id: 2,
    title: "Рабочие дни",
    value: "22",
  },
  {
    id: 3,
    title: "Выходные дни",
    value: "8",
  },
  {
    id: 4,
    title: "Праздничные дни",
    value: "1",
  },
];

export const arr = [
  {
    id: 1,
    whichDay: 5,
  },
  {
    id: 2,
    whichDay: 6,
  },
  {
    id: 3,
    whichDay: 7,
  },
  {
    id: 4,
    whichDay: 1,
  },
  {
    id: 5,
    whichDay: 2,
  },
  {
    id: 6,
    whichDay: 3,
  },
  {
    id: 7,
    whichDay: 4,
  },
  {
    id: 8,
    whichDay: 5,
  },
];
